spring:
    # 使用druid数据源
    datasource:
        name: downloader
        url: jdbc:mysql://localhost:3306/downloader
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
    mvc:
      view:
        prefix: /WEB-INF/templates/
        suffix: .jsp
mybatis:
  type-aliases-package: com.yang.downloader.entity
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080